# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_comment_like_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment_like_model',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='comment_like_model',
            name='updated_on',
        ),
        migrations.AddField(
            model_name='comment_like_model',
            name='user_like',
            field=models.BooleanField(default=False),
        ),
    ]
