# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20170727_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment_like_model',
            name='user_like',
        ),
        migrations.AddField(
            model_name='comment_like_model',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment_like_model',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
