# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 06:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20170727_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment_like_model',
            name='post',
        ),
    ]
